### ISSUE TITLE
Multiple-Cursor Line Select?

### ISSUE THREAD

**Issue by peterkrieg** [kaiwood/vscode-better-line-select#1]
Hello,

First of all, this is a super helpful extension, so thank you for making it!  

It would be nice to have multi-cursor line select, shown in the screencast below (editor is sublime)

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/7385488/29684544-5d7c5902-88e0-11e7-831f-6769e06345a7.gif)

If I have some free time maybe I'll learn how to code VS extensions and submit a PR.  Don't know how hard this is to add.

**Comment by kaiwood** [comment]
It took me a "little" while to find the time to implement this, but here we go. Thanks for the suggestion, @peterkrieg

**Comment by peterkrieg** [comment]
Forgot I wrote this 🙂  

Thanks so much @kaiwood,  it works great!
